var JD_DATA = [

  { label:"Developer Support", link:"support.html",
    tags:[], type:"" },
  { label:"Welcome", link:"offline.html",
    tags:[], type:"" },
  { label:"Dashboards", link:"about/dashboards/index.html",
    tags:[], type:"about" },
  { label:"Ice Cream Sandwich", link:"about/versions/android-4.0-highlights.html",
    tags:[], type:"about" },
  { label:"Gingerbread", link:"about/versions/android-2.3-highlights.html",
    tags:[], type:"about" },
  { label:"Jelly Bean", link:"about/versions/jelly-bean.html",
    tags:[], type:"about" },
  { label:"Android KitKat", link:"about/versions/kitkat.html",
    tags:[], type:"about" },
  { label:"Honeycomb", link:"about/versions/android-3.0-highlights.html",
    tags:[], type:"about" },
  { label:"Honeycomb MR1", link:"about/versions/android-3.1-highlights.html",
    tags:[], type:"about" },
  { label:"Android SDK", link:"sdk/index.html",
    tags:["download"], type:"sdk" },
  { label:"Android Studio Tips and Tricks", link:"sdk/installing/studio-tips.html",
    tags:[], type:"sdk" },
  { label:"Setting Up an Existing IDE", link:"sdk/installing/index.html",
    tags:[], type:"sdk" },
  { label:"Adding Platforms and Packages", link:"sdk/installing/adding-packages.html",
    tags:[], type:"sdk" },
  { label:"Migrating from Eclipse", link:"sdk/installing/migrate.html",
    tags:[], type:"sdk" },
  { label:"Setting Up the ADT Bundle", link:"sdk/installing/bundle.html",
    tags:[], type:"sdk" },
  { label:"Getting Started with Android Studio", link:"sdk/installing/studio.html",
    tags:["studio"], type:"sdk" },
  { label:"Installing the Eclipse Plugin", link:"sdk/installing/installing-adt.html",
    tags:[], type:"sdk" },
  { label:"Terms and Conditions", link:"sdk/terms.html",
    tags:[], type:"sdk" },
  { label:"Google USB Driver", link:"sdk/win-usb.html",
    tags:[], type:"sdk" },
  { label:"Google Services", link:"google/index.html",
    tags:[], type:"google" },
  { label:"Android Backup Service", link:"google/backup/index.html",
    tags:[], type:"google" },
  { label:"Application Licensing", link:"google/play/licensing/index.html",
    tags:[], type:"google" },
  { label:"Licensing Overview", link:"google/play/licensing/overview.html",
    tags:[], type:"google" },
  { label:"Adding Licensing to Your App", link:"google/play/licensing/adding-licensing.html",
    tags:[], type:"google" },
  { label:"Setting Up for Licensing", link:"google/play/licensing/setting-up.html",
    tags:[], type:"google" },
  { label:"Licensing Reference", link:"google/play/licensing/licensing-reference.html",
    tags:[], type:"google" },
  { label:"Multiple APK Support", link:"google/play/publishing/multiple-apks.html",
    tags:[], type:"google" },
  { label:"Google Play Distribution", link:"google/play/dist.html",
    tags:[], type:"google" },
  { label:"Filters on Google Play", link:"google/play/filters.html",
    tags:[], type:"google" },
  { label:"In-app Billing Overview", link:"google/play/billing/billing_overview.html",
    tags:[], type:"google" },
  { label:"Google Play In-app Billing", link:"google/play/billing/index.html",
    tags:[], type:"google" },
  { label:"In-app Billing Reference ", link:"google/play/billing/billing_reference.html",
    tags:[], type:"google" },
  { label:"Purchase Status API", link:"google/play/billing/gp-purchase-status-api.html",
    tags:["In-app Billing","Google Play","inapp billing","in app billing","iab","billing"], type:"google" },
  { label:"Subscriptions", link:"google/play/billing/billing_subscriptions.html",
    tags:[], type:"google" },
  { label:"Security and Design", link:"google/play/billing/billing_best_practices.html",
    tags:[], type:"google" },
  { label:"Administering In-app Billing", link:"google/play/billing/billing_admin.html",
    tags:[], type:"google" },
  { label:"In-app Billing Version 3", link:"google/play/billing/api.html",
    tags:[], type:"google" },
  { label:"Testing In-app Billing", link:"google/play/billing/billing_testing.html",
    tags:[], type:"google" },
  { label:"In-app Billing Version Notes", link:"google/play/billing/versions.html",
    tags:[], type:"google" },
  { label:"Implementing In-app Billing ", link:"google/play/billing/billing_integrate.html",
    tags:[], type:"google" },
  { label:"APK Expansion Files", link:"google/play/expansion-files.html",
    tags:[], type:"google" },
  { label:"Google Play Services", link:"google/play-services/index.html",
    tags:[], type:"google" },
  { label:"Google Maps Android API", link:"google/play-services/maps.html",
    tags:["mapview","location"], type:"google" },
  { label:"Google Play Game Services", link:"google/play-services/games.html",
    tags:[], type:"google" },
  { label:"Set Up Google Play Services SDK", link:"google/play-services/setup.html",
    tags:[], type:"google" },
  { label:"Location APIs", link:"google/play-services/location.html",
    tags:["location","geofence","geofencing","gps"], type:"google" },
  { label:"Authorization", link:"google/play-services/auth.html",
    tags:["AccountManager","oauth2"], type:"google" },
  { label:"Advertising ID", link:"google/play-services/id.html",
    tags:["Ads","Advertising ID","ID"], type:"google" },
  { label:"Google+ Platform for Android", link:"google/play-services/plus.html",
    tags:["authentication","signin","social"], type:"google" },
  { label:"Google Mobile Ads", link:"google/play-services/ads.html",
    tags:["Ads","monetization","AdMob","Google Play services"], type:"google" },
  { label:"Google Wallet Instant Buy for Android", link:"google/play-services/wallet.html",
    tags:["Wallet","payments","Instant Buy"], type:"google" },
  { label:"Google Cloud Messaging for Android", link:"google/gcm/index.html",
    tags:["gcm"], type:"google" },
  { label:"GCM Client", link:"google/gcm/client.html",
    tags:["cloud","push","messaging"], type:"google" },
  { label:"GCM Architectural Overview", link:"google/gcm/gcm.html",
    tags:[], type:"google" },
  { label:"GCM Demo Application", link:"google/gcm/demo.html",
    tags:[], type:"google" },
  { label:"Migration", link:"google/gcm/c2dm.html",
    tags:[], type:"google" },
  { label:"GCM Advanced Topics", link:"google/gcm/adv.html",
    tags:[], type:"google" },
  { label:"GCM Cloud Connection Server", link:"google/gcm/ccs.html",
    tags:[], type:"google" },
  { label:"Getting Started with GCM", link:"google/gcm/gs.html",
    tags:["cloud","push","messaging"], type:"google" },
  { label:"Using the GCM Helper Libraries", link:"google/gcm/helper.html",
    tags:["cloud","push","messaging"], type:"google" },
  { label:"User Notifications", link:"google/gcm/notifications.html",
    tags:[], type:"google" },
  { label:"GCM Server", link:"google/gcm/server.html",
    tags:[], type:"google" },
  { label:"Google I/O 13", link:"channels/io2013.html",
    tags:[], type:"channels" },
  { label:"Accessing Contacts Data", link:"training/contacts-provider/index.html",
    tags:[], type:"training" },
  { label:"Retrieving a List of Contacts", link:"training/contacts-provider/retrieve-names.html",
    tags:[], type:"training" },
  { label:"Modifying Contacts Using Intents", link:"training/contacts-provider/modify-data.html",
    tags:[], type:"training" },
  { label:"Retrieving Details for a Contact", link:"training/contacts-provider/retrieve-details.html",
    tags:[], type:"training" },
  { label:"Displaying the Quick Contact Badge", link:"training/contacts-provider/display-contact-badge.html",
    tags:[], type:"training" },
  { label:"Building a Dynamic UI with Fragments", link:"training/basics/fragments/index.html",
    tags:["fragments","user interface","support library"], type:"training" },
  { label:"Communicating with Other Fragments", link:"training/basics/fragments/communicating.html",
    tags:[], type:"training" },
  { label:"Creating a Fragment", link:"training/basics/fragments/creating.html",
    tags:[], type:"training" },
  { label:"Using the Support Library", link:"training/basics/fragments/support-lib.html",
    tags:["support library"], type:"training" },
  { label:"Building a Flexible UI", link:"training/basics/fragments/fragment-ui.html",
    tags:[], type:"training" },
  { label:"Saving Data", link:"training/basics/data-storage/index.html",
    tags:["data storage","files","sql","database","preferences"], type:"training" },
  { label:"Saving Key-Value Sets", link:"training/basics/data-storage/shared-preferences.html",
    tags:[], type:"training" },
  { label:"Saving Data in SQL Databases", link:"training/basics/data-storage/databases.html",
    tags:[], type:"training" },
  { label:"Saving Files", link:"training/basics/data-storage/files.html",
    tags:[], type:"training" },
  { label:"Supporting Different Devices", link:"training/basics/supporting-devices/index.html",
    tags:["resources","screens","versions","localization"], type:"training" },
  { label:"Supporting Different Languages", link:"training/basics/supporting-devices/languages.html",
    tags:["localizing","localization","resources","formats","l10n"], type:"training" },
  { label:"Supporting Different Screens", link:"training/basics/supporting-devices/screens.html",
    tags:[], type:"training" },
  { label:"Supporting Different Platform Versions", link:"training/basics/supporting-devices/platforms.html",
    tags:[], type:"training" },
  { label:"Connecting to the Network", link:"training/basics/network-ops/connecting.html",
    tags:[], type:"training" },
  { label:"Performing Network Operations", link:"training/basics/network-ops/index.html",
    tags:["network","wireless"], type:"training" },
  { label:"Parsing XML Data", link:"training/basics/network-ops/xml.html",
    tags:[], type:"training" },
  { label:"Managing Network Usage", link:"training/basics/network-ops/managing.html",
    tags:[], type:"training" },
  { label:"Interacting with Other Apps", link:"training/basics/intents/index.html",
    tags:["intents","activity"], type:"training" },
  { label:"Sending the User to Another App", link:"training/basics/intents/sending.html",
    tags:[], type:"training" },
  { label:"Allowing Other Apps to Start Your Activity", link:"training/basics/intents/filters.html",
    tags:[], type:"training" },
  { label:"Getting a Result from an Activity", link:"training/basics/intents/result.html",
    tags:[], type:"training" },
  { label:"Building a Simple User Interface", link:"training/basics/firstapp/building-ui.html",
    tags:[], type:"training" },
  { label:"Building Your First App", link:"training/basics/firstapp/index.html",
    tags:[], type:"training" },
  { label:"Starting Another Activity", link:"training/basics/firstapp/starting-activity.html",
    tags:[], type:"training" },
  { label:"Running Your App", link:"training/basics/firstapp/running-app.html",
    tags:[], type:"training" },
  { label:"Creating an Android Project", link:"training/basics/firstapp/creating-project.html",
    tags:[], type:"training" },
  { label:"Pausing and Resuming an Activity", link:"training/basics/activity-lifecycle/pausing.html",
    tags:[], type:"training" },
  { label:"Starting an Activity", link:"training/basics/activity-lifecycle/starting.html",
    tags:[], type:"training" },
  { label:"Recreating an Activity", link:"training/basics/activity-lifecycle/recreating.html",
    tags:[], type:"training" },
  { label:"Managing the Activity Lifecycle", link:"training/basics/activity-lifecycle/index.html",
    tags:[], type:"training" },
  { label:"Stopping and Restarting an Activity", link:"training/basics/activity-lifecycle/stopping.html",
    tags:[], type:"training" },
  { label:"Adding the Action Bar", link:"training/basics/actionbar/index.html",
    tags:["actionbar"], type:"training" },
  { label:"Overlaying the Action Bar", link:"training/basics/actionbar/overlaying.html",
    tags:[], type:"training" },
  { label:"Styling the Action Bar", link:"training/basics/actionbar/styling.html",
    tags:[], type:"training" },
  { label:"Adding Action Buttons", link:"training/basics/actionbar/adding-buttons.html",
    tags:[], type:"training" },
  { label:"Setting Up the Action Bar", link:"training/basics/actionbar/setting-up.html",
    tags:[], type:"training" },
  { label:"Connecting Devices Wirelessly", link:"training/connect-devices-wirelessly/index.html",
    tags:["wifi","network","wireless"], type:"training" },
  { label:"Using Wi-Fi P2P for Service Discovery", link:"training/connect-devices-wirelessly/nsd-wifi-direct.html",
    tags:[], type:"training" },
  { label:"Using Network Service Discovery", link:"training/connect-devices-wirelessly/nsd.html",
    tags:[], type:"training" },
  { label:"Creating P2P Connections with Wi-Fi", link:"training/connect-devices-wirelessly/wifi-direct.html",
    tags:[], type:"training" },
  { label:"Adding Search Functionality", link:"training/search/index.html",
    tags:["searchview","database"], type:"training" },
  { label:"Storing and Searching for Data", link:"training/search/search.html",
    tags:[], type:"training" },
  { label:"Setting Up the Search Interface", link:"training/search/setup.html",
    tags:[], type:"training" },
  { label:"Remaining Backward Compatible", link:"training/search/backward-compat.html",
    tags:[], type:"training" },
  { label:"Getting Started", link:"training/index.html",
    tags:[], type:"training" },
  { label:"Monetizing Your App", link:"training/monetization/index.html",
    tags:[], type:"training" },
  { label:"Advertising without Compromising User Experience", link:"training/monetization/ads-and-ux.html",
    tags:[], type:"training" },
  { label:"Syncing to the Cloud", link:"training/cloudsync/index.html",
    tags:["cloud","sync","backup"], type:"training" },
  { label:"Making the Most of Google Cloud Messaging", link:"training/cloudsync/gcm.html",
    tags:[], type:"training" },
  { label:"Using the Backup API", link:"training/cloudsync/backupapi.html",
    tags:[], type:"training" },
  { label:"Using Touch Gestures", link:"training/gestures/index.html",
    tags:["input","navigation","gesturedetector","scroller"], type:"training" },
  { label:"Animating a Scroll Gesture", link:"training/gestures/scroll.html",
    tags:[], type:"training" },
  { label:"Managing Touch Events in a ViewGroup", link:"training/gestures/viewgroup.html",
    tags:[], type:"training" },
  { label:"Detecting Common Gestures", link:"training/gestures/detector.html",
    tags:[], type:"training" },
  { label:"Handling Multi-Touch Gestures", link:"training/gestures/multi.html",
    tags:[], type:"training" },
  { label:"Dragging and Scaling", link:"training/gestures/scale.html",
    tags:[], type:"training" },
  { label:"Tracking Movement", link:"training/gestures/movement.html",
    tags:[], type:"training" },
  { label:"Designing for Multiple Screens", link:"training/multiscreen/index.html",
    tags:["tablet","tv","fragments","support"], type:"training" },
  { label:"Supporting Different Screen Sizes", link:"training/multiscreen/screensizes.html",
    tags:[], type:"training" },
  { label:"Implementing Adaptative UI Flows", link:"training/multiscreen/adaptui.html",
    tags:[], type:"training" },
  { label:"Supporting Different Densities", link:"training/multiscreen/screendensities.html",
    tags:[], type:"training" },
  { label:"Printing Content", link:"training/printing/index.html",
    tags:["print","navigation","gesturedetector","scroller"], type:"training" },
  { label:"Printing HTML Documents", link:"training/printing/html-docs.html",
    tags:[], type:"training" },
  { label:"Printing Custom Documents", link:"training/printing/custom-docs.html",
    tags:[], type:"training" },
  { label:"Printing Photos", link:"training/printing/photos.html",
    tags:[], type:"training" },
  { label:"Loading Data in the Background", link:"training/load-data-background/index.html",
    tags:["cursorloader"], type:"training" },
  { label:"Handling the Results", link:"training/load-data-background/handle-results.html",
    tags:[], type:"training" },
  { label:"Running a Query with a CursorLoader", link:"training/load-data-background/setup-loader.html",
    tags:[], type:"training" },
  { label:"Managing Device Awake State", link:"training/scheduling/index.html",
    tags:[""], type:"training" },
  { label:"Keeping the Device Awake", link:"training/scheduling/wakelock.html",
    tags:[], type:"training" },
  { label:"Scheduling Repeating Alarms", link:"training/scheduling/alarms.html",
    tags:[], type:"training" },
  { label:"Testing UI Components", link:"training/activity-testing/activity-ui-testing.html",
    tags:[], type:"training" },
  { label:"Testing Your Android Activity", link:"training/activity-testing/index.html",
    tags:["testing"], type:"training" },
  { label:"Creating Functional Tests", link:"training/activity-testing/activity-functional-testing.html",
    tags:[], type:"training" },
  { label:"Setting Up Your Test Environment", link:"training/activity-testing/preparing-activity-testing.html",
    tags:[], type:"training" },
  { label:"Creating and Running a Test Case", link:"training/activity-testing/activity-basic-testing.html",
    tags:[], type:"training" },
  { label:"Creating Unit Tests", link:"training/activity-testing/activity-unit-testing.html",
    tags:[], type:"training" },
  { label:"Minimizing the Effect of Regular Updates", link:"training/efficient-downloads/regular_updates.html",
    tags:[], type:"training" },
  { label:"Transferring Data Without Draining the Battery", link:"training/efficient-downloads/index.html",
    tags:["battery","network","wireless"], type:"training" },
  { label:"Optimizing Downloads for Efficient Network Access", link:"training/efficient-downloads/efficient-network-access.html",
    tags:[], type:"training" },
  { label:"Modifying your Download Patterns Based on the Connectivity Type", link:"training/efficient-downloads/connectivity_patterns.html",
    tags:[], type:"training" },
  { label:"Redundant Downloads are Redundant", link:"training/efficient-downloads/redundant_redundant.html",
    tags:[], type:"training" },
  { label:"Defining Shapes", link:"training/graphics/opengl/shapes.html",
    tags:[], type:"training" },
  { label:"Displaying Graphics with OpenGL ES", link:"training/graphics/opengl/index.html",
    tags:[], type:"training" },
  { label:"Building an OpenGL ES Environment", link:"training/graphics/opengl/environment.html",
    tags:[], type:"training" },
  { label:" Responding to Touch Events", link:"training/graphics/opengl/touch.html",
    tags:[], type:"training" },
  { label:"Applying Projection and Camera Views", link:"training/graphics/opengl/projection.html",
    tags:[], type:"training" },
  { label:"Drawing Shapes", link:"training/graphics/opengl/draw.html",
    tags:[], type:"training" },
  { label:"Adding Motion", link:"training/graphics/opengl/motion.html",
    tags:[], type:"training" },
  { label:"Building Apps with Graphics &amp; Animation", link:"training/building-graphics.html",
    tags:[], type:"training" },
  { label:"Remembering Users", link:"training/id-auth/index.html",
    tags:["privacy","oauth","accounts"], type:"training" },
  { label:"Authenticating to OAuth2 Services", link:"training/id-auth/authenticate.html",
    tags:[], type:"training" },
  { label:"Remembering Your User", link:"training/id-auth/identify.html",
    tags:[], type:"training" },
  { label:"Creating a Custom Account Type", link:"training/id-auth/custom_auth.html",
    tags:[], type:"training" },
  { label:"Building Apps with Multimedia", link:"training/building-multimedia.html",
    tags:[], type:"training" },
  { label:"Creating Backward-Compatible UIs", link:"training/backward-compatible-ui/index.html",
    tags:["widgets","support"], type:"training" },
  { label:"Proxying to the New APIs", link:"training/backward-compatible-ui/new-implementation.html",
    tags:[], type:"training" },
  { label:"Using the Version-Aware Component", link:"training/backward-compatible-ui/using-component.html",
    tags:[], type:"training" },
  { label:"Abstracting the New APIs", link:"training/backward-compatible-ui/abstracting.html",
    tags:[], type:"training" },
  { label:"Creating an Implementation with Older APIs", link:"training/backward-compatible-ui/older-implementation.html",
    tags:[], type:"training" },
  { label:"Best Practices for User Input", link:"training/best-user-input.html",
    tags:[], type:"training" },
  { label:"Keeping Your App Responsive", link:"training/articles/perf-anr.html",
    tags:["threads","asynctask"], type:"training" },
  { label:"SMP Primer for Android", link:"training/articles/smp.html",
    tags:["ndk","native"], type:"training" },
  { label:"Managing Your App's Memory", link:"training/articles/memory.html",
    tags:["ram","low memory","OutOfMemoryError","onTrimMemory"], type:"training" },
  { label:"﻿Security Tips", link:"training/articles/security-tips.html",
    tags:[], type:"training" },
  { label:"﻿Security with HTTPS and SSL", link:"training/articles/security-ssl.html",
    tags:["network","certificates"], type:"training" },
  { label:"Performance Tips", link:"training/articles/perf-tips.html",
    tags:[], type:"training" },
  { label:"JNI Tips", link:"training/articles/perf-jni.html",
    tags:["ndk","native"], type:"training" },
  { label:"Creating a Navigation Drawer", link:"training/implementing-navigation/nav-drawer.html",
    tags:["DrawerLayout","navigation"], type:"training" },
  { label:"Implementing Effective Navigation", link:"training/implementing-navigation/index.html",
    tags:[], type:"training" },
  { label:"Providing Proper Back Navigation", link:"training/implementing-navigation/temporal.html",
    tags:["back navigation","NavUtils","TaskStackBuilder"], type:"training" },
  { label:"Creating Swipe Views with Tabs", link:"training/implementing-navigation/lateral.html",
    tags:["viewpager","horizontal","paging","swipe view","tabs"], type:"training" },
  { label:"Implementing Descendant Navigation", link:"training/implementing-navigation/descendant.html",
    tags:[], type:"training" },
  { label:"Providing Up Navigation", link:"training/implementing-navigation/ancestral.html",
    tags:["up navigation","NavUtils","TaskStackBuilder"], type:"training" },
  { label:"Transferring Data Using Sync Adapters", link:"training/sync-adapters/index.html",
    tags:[], type:"training" },
  { label:"Creating a Stub Content Provider", link:"training/sync-adapters/creating-stub-provider.html",
    tags:[], type:"training" },
  { label:"Running a Sync Adapter", link:"training/sync-adapters/running-sync-adapter.html",
    tags:[], type:"training" },
  { label:"Creating a Sync Adapter", link:"training/sync-adapters/creating-sync-adapter.html",
    tags:[], type:"training" },
  { label:"Creating a Stub Authenticator", link:"training/sync-adapters/creating-authenticator.html",
    tags:[], type:"training" },
  { label:"Designing for TV", link:"training/tv/index.html",
    tags:["input","screens"], type:"training" },
  { label:"Optimizing Navigation for TV", link:"training/tv/optimizing-navigation-tv.html",
    tags:[], type:"training" },
  { label:"Optimizing Layouts for TV", link:"training/tv/optimizing-layouts-tv.html",
    tags:[], type:"training" },
  { label:"Handling Features Not Supported on TV", link:"training/tv/unsupported-features-tv.html",
    tags:[], type:"training" },
  { label:"Best Practices for Security &amp; Privacy", link:"training/best-security.html",
    tags:[], type:"training" },
  { label:"Crossfading Two Views", link:"training/animation/crossfade.html",
    tags:[], type:"training" },
  { label:"Adding Animations", link:"training/animation/index.html",
    tags:["Animator","views","layout","user interface"], type:"training" },
  { label:"Zooming a View", link:"training/animation/zoom.html",
    tags:[], type:"training" },
  { label:"Displaying Card Flip Animations", link:"training/animation/cardflip.html",
    tags:[], type:"training" },
  { label:"Animating Layout Changes", link:"training/animation/layout.html",
    tags:[], type:"training" },
  { label:"Using ViewPager for Screen Slides", link:"training/animation/screen-slide.html",
    tags:[], type:"training" },
  { label:"Sending Operations to Multiple Threads", link:"training/multiple-threads/index.html",
    tags:["threadpool","runnable"], type:"training" },
  { label:"Running Code on a Thread Pool Thread", link:"training/multiple-threads/run-code.html",
    tags:[], type:"training" },
  { label:"Specifying the Code to Run on a Thread", link:"training/multiple-threads/define-runnable.html",
    tags:[], type:"training" },
  { label:"Communicating with the UI Thread", link:"training/multiple-threads/communicate-ui.html",
    tags:[], type:"training" },
  { label:"Creating a Manager for Multiple Threads", link:"training/multiple-threads/create-threadpool.html",
    tags:[], type:"training" },
  { label:"Retrieving File Information", link:"training/secure-file-sharing/retrieve-info.html",
    tags:[], type:"training" },
  { label:"Sharing Files", link:"training/secure-file-sharing/index.html",
    tags:["FileProvider","share","ContentProvider"], type:"training" },
  { label:"Sharing a File", link:"training/secure-file-sharing/share-file.html",
    tags:[], type:"training" },
  { label:"Requesting a Shared File", link:"training/secure-file-sharing/request-file.html",
    tags:[], type:"training" },
  { label:"Setting Up File Sharing", link:"training/secure-file-sharing/setup-sharing.html",
    tags:[], type:"training" },
  { label:"Building Apps with Connectivity &amp; the Cloud", link:"training/building-connectivity.html",
    tags:[], type:"training" },
  { label:"Managing Audio Playback", link:"training/managing-audio/index.html",
    tags:["audio","media"], type:"training" },
  { label:"Controlling Your App’s Volume and Playback", link:"training/managing-audio/volume-playback.html",
    tags:[], type:"training" },
  { label:"Dealing with Audio Output Hardware", link:"training/managing-audio/audio-output.html",
    tags:[], type:"training" },
  { label:"Managing Audio Focus", link:"training/managing-audio/audio-focus.html",
    tags:[], type:"training" },
  { label:"Best Practices for Performance", link:"training/best-performance.html",
    tags:[], type:"training" },
  { label:"Resolving Cloud Save Conflicts", link:"training/cloudsave/conflict-res.html",
    tags:["cloud"], type:"training" },
  { label:"Advanced Training", link:"training/advanced.html",
    tags:[], type:"training" },
  { label:"Handling Keyboard Input", link:"training/keyboard-input/index.html",
    tags:["edittext","accessibility"], type:"training" },
  { label:"Specifying the Input Method Type", link:"training/keyboard-input/style.html",
    tags:[], type:"training" },
  { label:"Handling Input Method Visibility", link:"training/keyboard-input/visibility.html",
    tags:[], type:"training" },
  { label:"Supporting Keyboard Navigation", link:"training/keyboard-input/navigation.html",
    tags:[], type:"training" },
  { label:"Handling Keyboard Actions", link:"training/keyboard-input/commands.html",
    tags:[], type:"training" },
  { label:"Building Apps with User Info &amp; Location", link:"training/building-userinfo.html",
    tags:[], type:"training" },
  { label:"Displaying Bitmaps Efficiently", link:"training/displaying-bitmaps/index.html",
    tags:["bitmaps","images","graphics"], type:"training" },
  { label:"Loading Large Bitmaps Efficiently", link:"training/displaying-bitmaps/load-bitmap.html",
    tags:[], type:"training" },
  { label:"Caching Bitmaps", link:"training/displaying-bitmaps/cache-bitmap.html",
    tags:[], type:"training" },
  { label:"Managing Bitmap Memory", link:"training/displaying-bitmaps/manage-memory.html",
    tags:[], type:"training" },
  { label:"Displaying Bitmaps in Your UI", link:"training/displaying-bitmaps/display-bitmap.html",
    tags:[], type:"training" },
  { label:"Processing Bitmaps Off the UI Thread", link:"training/displaying-bitmaps/process-bitmap.html",
    tags:[], type:"training" },
  { label:"Improving Layout Performance", link:"training/improving-layouts/index.html",
    tags:["include","merge","viewstub","listview"], type:"training" },
  { label:"Making ListView Scrolling Smooth", link:"training/improving-layouts/smooth-scrolling.html",
    tags:[], type:"training" },
  { label:"Re-using Layouts with &lt;include/&gt;", link:"training/improving-layouts/reusing-layouts.html",
    tags:[], type:"training" },
  { label:"Loading Views On Demand", link:"training/improving-layouts/loading-ondemand.html",
    tags:[], type:"training" },
  { label:"Optimizing Layout Hierarchies", link:"training/improving-layouts/optimizing-layout.html",
    tags:[], type:"training" },
  { label:"Best Practices for Background Jobs", link:"training/best-background.html",
    tags:[], type:"training" },
  { label:"Sharing Files with NFC", link:"training/beam-files/index.html",
    tags:["NfcAdapter","Android Beam","share","file transfer"], type:"training" },
  { label:"Receiving Files from Another Device", link:"training/beam-files/receive-files.html",
    tags:[], type:"training" },
  { label:"Sending Files to Another Device", link:"training/beam-files/send-files.html",
    tags:[], type:"training" },
  { label:"Best Practices for Testing", link:"training/testing.html",
    tags:[], type:"training" },
  { label:"Notepad Tutorial", link:"training/notepad/index.html",
    tags:[], type:"training" },
  { label:"Notepad Exercise 3", link:"training/notepad/notepad-ex3.html",
    tags:[], type:"training" },
  { label:"Notepad Tutorial", link:"training/notepad/notepad-index.html",
    tags:[], type:"training" },
  { label:"Notepad Exercise 1", link:"training/notepad/notepad-ex1.html",
    tags:[], type:"training" },
  { label:"Notepad Extra Credit", link:"training/notepad/notepad-extra-credit.html",
    tags:[], type:"training" },
  { label:"Managing the System UI", link:"training/system-ui/index.html",
    tags:[""], type:"training" },
  { label:"Dimming the System Bars", link:"training/system-ui/dim.html",
    tags:[], type:"training" },
  { label:"Hiding the Status Bar", link:"training/system-ui/status.html",
    tags:[], type:"training" },
  { label:"Responding to UI Visibility Changes", link:"training/system-ui/visibility.html",
    tags:[], type:"training" },
  { label:"Hiding the Navigation Bar", link:"training/system-ui/navigation.html",
    tags:[], type:"training" },
  { label:"Reporting Work Status", link:"training/run-background-service/report-status.html",
    tags:[], type:"training" },
  { label:"Running in a Background Service", link:"training/run-background-service/index.html",
    tags:["intentservice"], type:"training" },
  { label:"Sending Work Requests to the Background Service", link:"training/run-background-service/send-request.html",
    tags:[], type:"training" },
  { label:"Creating a Background Service", link:"training/run-background-service/create-service.html",
    tags:[], type:"training" },
  { label:"Building Apps with Content Sharing", link:"training/building-content-sharing.html",
    tags:[], type:"training" },
  { label:"Using Google Play to Distribute &amp; Monetize", link:"training/distribute.html",
    tags:[], type:"training" },
  { label:"Best Practices for User Experience &amp; UI", link:"training/best-ux.html",
    tags:[], type:"training" },
  { label:"Implementing Accessibility", link:"training/accessibility/index.html",
    tags:["navigation","input"], type:"training" },
  { label:"Developing an Accessibility Service", link:"training/accessibility/service.html",
    tags:[], type:"training" },
  { label:"Developing Accessible Applications", link:"training/accessibility/accessible-app.html",
    tags:[], type:"training" },
  { label:"Taking Photos Simply", link:"training/camera/photobasics.html",
    tags:[], type:"training" },
  { label:"Capturing Photos", link:"training/camera/index.html",
    tags:["camera","video","picture"], type:"training" },
  { label:"Controlling the Camera", link:"training/camera/cameradirect.html",
    tags:[], type:"training" },
  { label:"Recording Videos Simply", link:"training/camera/videobasics.html",
    tags:[], type:"training" },
  { label:"Notifying the User", link:"training/notify-user/index.html",
    tags:["notifications"], type:"training" },
  { label:"Displaying Progress in a Notification", link:"training/notify-user/display-progress.html",
    tags:[], type:"training" },
  { label:"Building a Notification", link:"training/notify-user/build-notification.html",
    tags:[], type:"training" },
  { label:"Using Big View Styles", link:"training/notify-user/expanded.html",
    tags:[], type:"training" },
  { label:"Updating Notifications", link:"training/notify-user/managing.html",
    tags:[], type:"training" },
  { label:"Preserving Navigation when Starting an Activity", link:"training/notify-user/navigation.html",
    tags:[], type:"training" },
  { label:"Monitoring the Battery Level and Charging State", link:"training/monitoring-device-state/battery-monitoring.html",
    tags:[], type:"training" },
  { label:"Optimizing Battery Life", link:"training/monitoring-device-state/index.html",
    tags:["network","internet"], type:"training" },
  { label:"Determining and Monitoring the Docking State and Type", link:"training/monitoring-device-state/docking-monitoring.html",
    tags:[], type:"training" },
  { label:"Manipulating Broadcast Receivers On Demand", link:"training/monitoring-device-state/manifest-receivers.html",
    tags:[], type:"training" },
  { label:"Determining and Monitoring the Connectivity Status", link:"training/monitoring-device-state/connectivity-monitoring.html",
    tags:[], type:"training" },
  { label:"Sharing Simple Data", link:"training/sharing/index.html",
    tags:["intents","share"], type:"training" },
  { label:"Receiving Simple Data from Other Apps", link:"training/sharing/receive.html",
    tags:[], type:"training" },
  { label:"Adding an Easy Share Action", link:"training/sharing/shareaction.html",
    tags:[], type:"training" },
  { label:"Sending Simple Data to Other Apps", link:"training/sharing/send.html",
    tags:[], type:"training" },
  { label:"Developing for Enterprise", link:"training/enterprise/index.html",
    tags:["policy","privacy"], type:"training" },
  { label:"Enhancing Security with Device Management Policies", link:"training/enterprise/device-management-policy.html",
    tags:[], type:"training" },
  { label:"Retrieving the Current Location", link:"training/location/retrieve-current.html",
    tags:[], type:"training" },
  { label:"Making Your App Location-Aware", link:"training/location/index.html",
    tags:["location","geofence","geofencing","activity recognition","activity detection","gps"], type:"training" },
  { label:"Receiving Location Updates", link:"training/location/receive-location-updates.html",
    tags:[], type:"training" },
  { label:"Testing Using Mock Locations", link:"training/location/location-testing.html",
    tags:[], type:"training" },
  { label:"Displaying a Location Address", link:"training/location/display-address.html",
    tags:[], type:"training" },
  { label:"Creating and Monitoring Geofences", link:"training/location/geofencing.html",
    tags:[], type:"training" },
  { label:"Recognizing the User's Current Activity", link:"training/location/activity-recognition.html",
    tags:[], type:"training" },
  { label:"Designing Effective Navigation", link:"training/design-navigation/index.html",
    tags:[], type:"training" },
  { label:"Planning Screens and Their Relationships", link:"training/design-navigation/screen-planning.html",
    tags:[], type:"training" },
  { label:"Planning for Multiple Touchscreen Sizes", link:"training/design-navigation/multiple-sizes.html",
    tags:[], type:"training" },
  { label:"Putting it All Together: Wireframing the Example App", link:"training/design-navigation/wireframing.html",
    tags:[], type:"training" },
  { label:"Providing Descendant and Lateral Navigation", link:"training/design-navigation/descendant-lateral.html",
    tags:[], type:"training" },
  { label:"Providing Ancestral and Temporal Navigation", link:"training/design-navigation/ancestral-temporal.html",
    tags:[], type:"training" },
  { label:"Creating Custom Views", link:"training/custom-views/index.html",
    tags:["widgets","ui","layout"], type:"training" },
  { label:"Optimizing the View", link:"training/custom-views/optimizing-view.html",
    tags:[], type:"training" },
  { label:"Creating a View Class", link:"training/custom-views/create-view.html",
    tags:[], type:"training" },
  { label:"Making the View Interactive", link:"training/custom-views/making-interactive.html",
    tags:[], type:"training" },
  { label:"Custom Drawing", link:"training/custom-views/custom-drawing.html",
    tags:[], type:"training" },
  { label:"Creating Multiple APKs for Different Screen Sizes", link:"training/multiple-apks/screensize.html",
    tags:[], type:"training" },
  { label:"Maintaining Multiple APKs", link:"training/multiple-apks/index.html",
    tags:["support"], type:"training" },
  { label:"Creating Multiple APKs with 2+ Dimensions", link:"training/multiple-apks/multiple.html",
    tags:[], type:"training" },
  { label:"Creating Multiple APKs for Different API Levels", link:"training/multiple-apks/api.html",
    tags:[], type:"training" },
  { label:"Creating Multiple APKs for Different GL Textures", link:"training/multiple-apks/texture.html",
    tags:[], type:"training" },
  { label:"Selling In-app Products", link:"training/in-app-billing/index.html",
    tags:["billing"], type:"training" },
  { label:"Testing Your In-app Billing Application", link:"training/in-app-billing/test-iab-app.html",
    tags:[], type:"training" },
  { label:"Establishing In-app Billing Products for Sale", link:"training/in-app-billing/list-iab-products.html",
    tags:[], type:"training" },
  { label:"Preparing Your In-app Billing Application", link:"training/in-app-billing/preparing-iab-app.html",
    tags:[], type:"training" },
  { label:"Purchasing In-app Billing Products", link:"training/in-app-billing/purchase-iab-products.html",
    tags:[], type:"training" },
  { label:"Develop", link:"develop/index.html",
    tags:[], type:"develop" },
  { label:"Content License", link:"license.html",
    tags:[], type:"" },
  { label:"Legal Notice", link:"legal.html",
    tags:[], type:"" },
  { label:"Device Art Generator", link:"distribute/promote/device-art.html",
    tags:[], type:"distribute" },
  { label:"Distribute Apps", link:"distribute/index.html",
    tags:[], type:"distribute" },
  { label:"Open Distribution", link:"distribute/open.html",
    tags:[], type:"distribute" },
  { label:"App Quality", link:"distribute/googleplay/quality/index.html",
    tags:[], type:"distribute" },
  { label:"Core App Quality Guidelines", link:"distribute/googleplay/quality/core.html",
    tags:[], type:"distribute" },
  { label:"Tablet App Quality Checklist", link:"distribute/googleplay/quality/tablet.html",
    tags:[], type:"distribute" },
  { label:"Spotlight", link:"distribute/googleplay/spotlight/index.html",
    tags:[], type:"distribute" },
  { label:"Developer Stories: Google Play Game Services", link:"distribute/googleplay/spotlight/games.html",
    tags:[], type:"distribute" },
  { label:"Developer Stories: The Opportunity of Android Tablets", link:"distribute/googleplay/spotlight/tablets.html",
    tags:[], type:"distribute" },
  { label:"Brand Guidelines", link:"distribute/googleplay/promote/brand.html",
    tags:[], type:"distribute" },
  { label:"Promoting Your Apps", link:"distribute/googleplay/promote/index.html",
    tags:[], type:"distribute" },
  { label:"Your Product Pages", link:"distribute/googleplay/promote/product-pages.html",
    tags:[], type:"distribute" },
  { label:"Google Play Badge Files", link:"distribute/googleplay/promote/badge-files.html",
    tags:[], type:"distribute" },
  { label:"Linking to Your Products", link:"distribute/googleplay/promote/linking.html",
    tags:[], type:"distribute" },
  { label:"Google Play Badges", link:"distribute/googleplay/promote/badges.html",
    tags:[], type:"distribute" },
  { label:"Distribution Control", link:"distribute/googleplay/about/distribution.html",
    tags:[], type:"distribute" },
  { label:"Visibility for Your Apps", link:"distribute/googleplay/about/visibility.html",
    tags:[], type:"distribute" },
  { label:"Flexible Monetizing and Business Tools", link:"distribute/googleplay/about/monetizing.html",
    tags:[], type:"distribute" },
  { label:"Google Play Policies and Guidelines", link:"distribute/googleplay/policies/index.html",
    tags:[], type:"distribute" },
  { label:"Intellectual Property", link:"distribute/googleplay/policies/ip.html",
    tags:[], type:"distribute" },
  { label:"Spam", link:"distribute/googleplay/policies/spam.html",
    tags:[], type:"distribute" },
  { label:"Ads", link:"distribute/googleplay/policies/ads.html",
    tags:[], type:"distribute" },
  { label:"Publishing on Google Play", link:"distribute/googleplay/publish/index.html",
    tags:[], type:"distribute" },
  { label:"Launch Checklist", link:"distribute/googleplay/publish/preparing.html",
    tags:["publishing","launch","Google Play","Developer Console"], type:"distribute" },
  { label:"Developer Console", link:"distribute/googleplay/publish/console.html",
    tags:[], type:"distribute" },
  { label:"Localization Checklist", link:"distribute/googleplay/publish/localizing.html",
    tags:["localize","localization","resources","formats","l10n"], type:"distribute" },
  { label:"Get Started with Publishing", link:"distribute/googleplay/publish/register.html",
    tags:[], type:"distribute" },
  { label:"Success Strategies", link:"distribute/googleplay/strategies/index.html",
    tags:[], type:"distribute" },
  { label:"Preparing for Featuring", link:"distribute/googleplay/strategies/featuring.html",
    tags:[], type:"distribute" },
  { label:"Improving App Quality After Launch", link:"distribute/googleplay/strategies/app-quality.html",
    tags:[], type:"distribute" },
  { label:"Google Play for Education", link:"distribute/googleplay/edu/index.html",
    tags:["Google Play","education","schools","distribution"], type:"distribute" },
  { label:"Samples", link:"samples/index.html",
    tags:["samples","examples","code"], type:"samples" },
  { label:"UI", link:"samples/ui.html",
    tags:[], type:"samples" },
  { label:"Connectivity", link:"samples/connectivity.html",
    tags:[], type:"samples" },
  { label:"Input", link:"samples/input.html",
    tags:[], type:"samples" },
  { label:"Views", link:"samples/views.html",
    tags:[], type:"samples" },
  { label:"Content", link:"samples/content.html",
    tags:[], type:"samples" },
  { label:"Testing", link:"samples/testing.html",
    tags:[], type:"samples" },
  { label:"Media", link:"samples/media.html",
    tags:[], type:"samples" },
  { label:"Background", link:"samples/background.html",
    tags:[], type:"samples" },
  { label:"Security", link:"samples/security.html",
    tags:[], type:"samples" },
  { label:"Appendix", link:"guide/appendix/index.html",
    tags:[], type:"guide" },
  { label:"Supported Media Formats", link:"guide/appendix/media-formats.html",
    tags:["video","audio","mpeg","mp4","m4a","mp3","3gp","3gpp","flac","wave","wav"], type:"guide" },
  { label:"Search Overview", link:"guide/topics/search/index.html",
    tags:[], type:"guide" },
  { label:"Creating a Search Interface", link:"guide/topics/search/search-dialog.html",
    tags:["searchview"], type:"guide" },
  { label:"Searchable Configuration", link:"guide/topics/search/searchable-config.html",
    tags:[], type:"guide" },
  { label:"Adding Custom Suggestions", link:"guide/topics/search/adding-custom-suggestions.html",
    tags:["SearchRecentSuggestionsProvider"], type:"guide" },
  { label:"Adding Recent Query Suggestions", link:"guide/topics/search/adding-recent-query-suggestions.html",
    tags:["SearchRecentSuggestions","SearchRecentSuggestionsProvider"], type:"guide" },
  { label:"&lt;uses-feature&gt;", link:"guide/topics/manifest/uses-feature-element.html",
    tags:["filtering","features","google play filters","permissions"], type:"guide" },
  { label:"&lt;meta-data&gt;", link:"guide/topics/manifest/meta-data-element.html",
    tags:[], type:"guide" },
  { label:"&lt;category&gt;", link:"guide/topics/manifest/category-element.html",
    tags:[], type:"guide" },
  { label:"&lt;uses-permission&gt;", link:"guide/topics/manifest/uses-permission-element.html",
    tags:[], type:"guide" },
  { label:"&lt;supports-gl-texture&gt;", link:"guide/topics/manifest/supports-gl-texture-element.html",
    tags:[], type:"guide" },
  { label:"The AndroidManifest.xml File", link:"guide/topics/manifest/manifest-intro.html",
    tags:[], type:"guide" },
  { label:"&lt;activity&gt;", link:"guide/topics/manifest/activity-element.html",
    tags:[], type:"guide" },
  { label:"&lt;permission&gt;", link:"guide/topics/manifest/permission-element.html",
    tags:[], type:"guide" },
  { label:"&lt;uses-configuration&gt;", link:"guide/topics/manifest/uses-configuration-element.html",
    tags:[], type:"guide" },
  { label:"&lt;manifest&gt;", link:"guide/topics/manifest/manifest-element.html",
    tags:[], type:"guide" },
  { label:"&lt;provider&gt;", link:"guide/topics/manifest/provider-element.html",
    tags:[], type:"guide" },
  { label:"&lt;data&gt;", link:"guide/topics/manifest/data-element.html",
    tags:[], type:"guide" },
  { label:"&lt;path-permission&gt;", link:"guide/topics/manifest/path-permission-element.html",
    tags:[], type:"guide" },
  { label:"&lt;intent-filter&gt;", link:"guide/topics/manifest/intent-filter-element.html",
    tags:[], type:"guide" },
  { label:"&lt;uses-sdk&gt;", link:"guide/topics/manifest/uses-sdk-element.html",
    tags:["api levels","sdk version","minsdkversion","targetsdkversion","maxsdkversion"], type:"guide" },
  { label:"&lt;action&gt;", link:"guide/topics/manifest/action-element.html",
    tags:[], type:"guide" },
  { label:"&lt;grant-uri-permission&gt;", link:"guide/topics/manifest/grant-uri-permission-element.html",
    tags:[], type:"guide" },
  { label:"&lt;service&gt;", link:"guide/topics/manifest/service-element.html",
    tags:[], type:"guide" },
  { label:"&lt;receiver&gt;", link:"guide/topics/manifest/receiver-element.html",
    tags:[], type:"guide" },
  { label:"&lt;compatible-screens&gt;", link:"guide/topics/manifest/compatible-screens-element.html",
    tags:[], type:"guide" },
  { label:"&lt;permission-tree&gt;", link:"guide/topics/manifest/permission-tree-element.html",
    tags:[], type:"guide" },
  { label:"&lt;activity-alias&gt;", link:"guide/topics/manifest/activity-alias-element.html",
    tags:[], type:"guide" },
  { label:"&lt;permission-group&gt;", link:"guide/topics/manifest/permission-group-element.html",
    tags:[], type:"guide" },
  { label:"&lt;supports-screens&gt;", link:"guide/topics/manifest/supports-screens-element.html",
    tags:[], type:"guide" },
  { label:"&lt;instrumentation&gt;", link:"guide/topics/manifest/instrumentation-element.html",
    tags:[], type:"guide" },
  { label:"&lt;uses-library&gt;", link:"guide/topics/manifest/uses-library-element.html",
    tags:[], type:"guide" },
  { label:"&lt;application&gt;", link:"guide/topics/manifest/application-element.html",
    tags:[], type:"guide" },
  { label:"Animation and Graphics", link:"guide/topics/graphics/index.html",
    tags:[], type:"guide" },
  { label:"Drawable Animation", link:"guide/topics/graphics/drawable-animation.html",
    tags:[], type:"guide" },
  { label:"Animation and Graphics Overview", link:"guide/topics/graphics/overview.html",
    tags:[], type:"guide" },
  { label:"Canvas and Drawables", link:"guide/topics/graphics/2d-graphics.html",
    tags:[], type:"guide" },
  { label:"Property Animation", link:"guide/topics/graphics/prop-animation.html",
    tags:["valueanimator","objectanimator","layouttransition","ViewPropertyAnimator"], type:"guide" },
  { label:"OpenGL ES", link:"guide/topics/graphics/opengl.html",
    tags:["games"], type:"guide" },
  { label:"View Animation", link:"guide/topics/graphics/view-animation.html",
    tags:[], type:"guide" },
  { label:"Hardware Acceleration", link:"guide/topics/graphics/hardware-accel.html",
    tags:[], type:"guide" },
  { label:"Media and Camera", link:"guide/topics/media/index.html",
    tags:[], type:"guide" },
  { label:"Media Playback", link:"guide/topics/media/mediaplayer.html",
    tags:["mediaplayer","soundpool","audiomanager"], type:"guide" },
  { label:"SONiVOX JETCreator User Manual", link:"guide/topics/media/jet/jetcreator_manual.html",
    tags:[], type:"guide" },
  { label:"Audio Capture", link:"guide/topics/media/audio-capture.html",
    tags:["mediarecorder"], type:"guide" },
  { label:"Camera", link:"guide/topics/media/camera.html",
    tags:["photo","video","picture","mediarecorder"], type:"guide" },
  { label:"JetPlayer", link:"guide/topics/media/jetplayer.html",
    tags:[], type:"guide" },
  { label:"Processes and Application Life Cycle", link:"guide/topics/processes/process-lifecycle.html",
    tags:[], type:"guide" },
  { label:"Motion Sensors", link:"guide/topics/sensors/sensors_motion.html",
    tags:["sensorevent","accelerometer","gyroscope","gravity","rotation"], type:"guide" },
  { label:"Location and Sensors APIs", link:"guide/topics/sensors/index.html",
    tags:["location","sensors"], type:"guide" },
  { label:"Position Sensors", link:"guide/topics/sensors/sensors_position.html",
    tags:["sensorevent","orientation","proximity"], type:"guide" },
  { label:"Environment Sensors", link:"guide/topics/sensors/sensors_environment.html",
    tags:[], type:"guide" },
  { label:"Sensors Overview", link:"guide/topics/sensors/sensors_overview.html",
    tags:[], type:"guide" },
  { label:"Administration", link:"guide/topics/admin/index.html",
    tags:[], type:"guide" },
  { label:"Device Administration", link:"guide/topics/admin/device-admin.html",
    tags:["devicepolicymanager","policy","security"], type:"guide" },
  { label:"Permissions", link:"guide/topics/security/permissions.html",
    tags:[], type:"guide" },
  { label:"App Widgets", link:"guide/topics/appwidgets/index.html",
    tags:["home","AppWidgetProvider"], type:"guide" },
  { label:"App Widget Host", link:"guide/topics/appwidgets/host.html",
    tags:["AppWidgetHost","home screen","launcher"], type:"guide" },
  { label:"Connectivity", link:"guide/topics/connectivity/index.html",
    tags:[], type:"guide" },
  { label:"USB Host and Accessory", link:"guide/topics/connectivity/usb/index.html",
    tags:[], type:"guide" },
  { label:"USB Accessory", link:"guide/topics/connectivity/usb/accessory.html",
    tags:[], type:"guide" },
  { label:"USB Host", link:"guide/topics/connectivity/usb/host.html",
    tags:[], type:"guide" },
  { label:"NFC Basics", link:"guide/topics/connectivity/nfc/nfc.html",
    tags:[], type:"guide" },
  { label:"Near Field Communication", link:"guide/topics/connectivity/nfc/index.html",
    tags:[], type:"guide" },
  { label:"Advanced NFC", link:"guide/topics/connectivity/nfc/advanced-nfc.html",
    tags:[], type:"guide" },
  { label:"Host-based Card Emulation", link:"guide/topics/connectivity/nfc/hce.html",
    tags:["host card emulation","hce","HostApduService","OffHostApduService","tap and pay"], type:"guide" },
  { label:"Bluetooth", link:"guide/topics/connectivity/bluetooth.html",
    tags:["wireless","bluetoothadapter","bluetoothdevice"], type:"guide" },
  { label:"Session Initiation Protocol", link:"guide/topics/connectivity/sip.html",
    tags:["sipmanager","sipprofile","sipaudiocall","telephony"], type:"guide" },
  { label:"Bluetooth Low Energy", link:"guide/topics/connectivity/bluetooth-le.html",
    tags:["wireless","bluetoothadapter","bluetoothdevice","BLE","BTLE"], type:"guide" },
  { label:"Wi-Fi Peer-to-Peer", link:"guide/topics/connectivity/wifip2p.html",
    tags:["wireless","WifiP2pManager","Wi-Fi Direct","WiFi Direct","P2P","Wi-Fi P2P","WiFi P2P"], type:"guide" },
  { label:"Data Storage", link:"guide/topics/data/index.html",
    tags:[], type:"guide" },
  { label:"Storage Options", link:"guide/topics/data/data-storage.html",
    tags:["database","sharedpreferences","sdcard"], type:"guide" },
  { label:"Data Backup", link:"guide/topics/data/backup.html",
    tags:[], type:"guide" },
  { label:"App Install Location", link:"guide/topics/data/install-location.html",
    tags:["sdcard","external"], type:"guide" },
  { label:"Copy and Paste", link:"guide/topics/text/copy-paste.html",
    tags:["clipboardmanager","clipdata","input"], type:"guide" },
  { label:"Text and Input", link:"guide/topics/text/index.html",
    tags:[], type:"guide" },
  { label:"Spelling Checker Framework", link:"guide/topics/text/spell-checker-framework.html",
    tags:["input","spellcheckerservice"], type:"guide" },
  { label:"Creating an Input Method", link:"guide/topics/text/creating-input-method.html",
    tags:["ime","keyboard","inputmethodservice"], type:"guide" },
  { label:"Creating a Content Provider", link:"guide/topics/providers/content-provider-creating.html",
    tags:[], type:"guide" },
  { label:"Content Providers", link:"guide/topics/providers/content-providers.html",
    tags:[], type:"guide" },
  { label:"Contacts Provider", link:"guide/topics/providers/contacts-provider.html",
    tags:[], type:"guide" },
  { label:"Storage Access Framework", link:"guide/topics/providers/document-provider.html",
    tags:[], type:"guide" },
  { label:"Calendar Provider", link:"guide/topics/providers/calendar-provider.html",
    tags:[], type:"guide" },
  { label:"Content Provider Basics", link:"guide/topics/providers/content-provider-basics.html",
    tags:[], type:"guide" },
  { label:"Computation", link:"guide/topics/renderscript/index.html",
    tags:[], type:"guide" },
  { label:"RenderScript", link:"guide/topics/renderscript/compute.html",
    tags:[], type:"guide" },
  { label:"Runtime API Reference", link:"guide/topics/renderscript/reference.html",
    tags:[], type:"guide" },
  { label:"Advanced RenderScript", link:"guide/topics/renderscript/advanced.html",
    tags:[], type:"guide" },
  { label:"User Interface", link:"guide/topics/ui/index.html",
    tags:[], type:"guide" },
  { label:"Custom Components", link:"guide/topics/ui/custom-components.html",
    tags:["view","widget"], type:"guide" },
  { label:"Settings", link:"guide/topics/ui/settings.html",
    tags:["preference","preferenceactivity","preferencefragment"], type:"guide" },
  { label:"UI Overview", link:"guide/topics/ui/overview.html",
    tags:[], type:"guide" },
  { label:"Toasts", link:"guide/topics/ui/notifiers/toasts.html",
    tags:[], type:"guide" },
  { label:"Notifications", link:"guide/topics/ui/notifiers/notifications.html",
    tags:[], type:"guide" },
  { label:"Layouts", link:"guide/topics/ui/declaring-layout.html",
    tags:["view","viewgroup"], type:"guide" },
  { label:"Action Bar", link:"guide/topics/ui/actionbar.html",
    tags:["actionbar","menu","tabs"], type:"guide" },
  { label:"Input Controls", link:"guide/topics/ui/controls.html",
    tags:[], type:"guide" },
  { label:"Styles and Themes", link:"guide/topics/ui/themes.html",
    tags:[], type:"guide" },
  { label:"Dialogs", link:"guide/topics/ui/dialogs.html",
    tags:["alertdialog","dialogfragment"], type:"guide" },
  { label:"Drag and Drop", link:"guide/topics/ui/drag-drop.html",
    tags:["clipdata","dragevent","onlongclicklistener"], type:"guide" },
  { label:"Accessibility", link:"guide/topics/ui/accessibility/index.html",
    tags:[], type:"guide" },
  { label:"Making Applications Accessible", link:"guide/topics/ui/accessibility/apps.html",
    tags:[], type:"guide" },
  { label:"Accessibility Developer Checklist", link:"guide/topics/ui/accessibility/checklist.html",
    tags:[], type:"guide" },
  { label:"Building Accessibility Services", link:"guide/topics/ui/accessibility/services.html",
    tags:[], type:"guide" },
  { label:"Radio Buttons", link:"guide/topics/ui/controls/radiobutton.html",
    tags:["radiobutton","radiogroup"], type:"guide" },
  { label:"Toggle Buttons", link:"guide/topics/ui/controls/togglebutton.html",
    tags:["switch","togglebutton"], type:"guide" },
  { label:"Checkboxes", link:"guide/topics/ui/controls/checkbox.html",
    tags:[], type:"guide" },
  { label:"Pickers", link:"guide/topics/ui/controls/pickers.html",
    tags:["datepicker","timepicker"], type:"guide" },
  { label:"Spinners", link:"guide/topics/ui/controls/spinner.html",
    tags:["adapterview","spinneradapter"], type:"guide" },
  { label:"Buttons", link:"guide/topics/ui/controls/button.html",
    tags:["button","imagebutton"], type:"guide" },
  { label:"Text Fields", link:"guide/topics/ui/controls/text.html",
    tags:["edittext","autocompletetextview"], type:"guide" },
  { label:"Grid View", link:"guide/topics/ui/layout/gridview.html",
    tags:["gridview"], type:"guide" },
  { label:"Relative Layout", link:"guide/topics/ui/layout/relative.html",
    tags:["relativelayout"], type:"guide" },
  { label:"Linear Layout", link:"guide/topics/ui/layout/linear.html",
    tags:["linearlayout"], type:"guide" },
  { label:"List View", link:"guide/topics/ui/layout/listview.html",
    tags:["listview"], type:"guide" },
  { label:"Table", link:"guide/topics/ui/layout/grid.html",
    tags:[], type:"guide" },
  { label:"How Android Draws Views", link:"guide/topics/ui/how-android-draws.html",
    tags:[], type:"guide" },
  { label:"Menus", link:"guide/topics/ui/menus.html",
    tags:[], type:"guide" },
  { label:"AdapterView", link:"guide/topics/ui/binding.html",
    tags:[], type:"guide" },
  { label:"Input Events", link:"guide/topics/ui/ui-events.html",
    tags:[], type:"guide" },
  { label:"Accessing Resources", link:"guide/topics/resources/accessing-resources.html",
    tags:[], type:"guide" },
  { label:"More Resource Types", link:"guide/topics/resources/more-resources.html",
    tags:[], type:"guide" },
  { label:"App Resources", link:"guide/topics/resources/index.html",
    tags:[], type:"guide" },
  { label:"Resources Overview", link:"guide/topics/resources/overview.html",
    tags:[], type:"guide" },
  { label:"Style Resource", link:"guide/topics/resources/style-resource.html",
    tags:[], type:"guide" },
  { label:"Animation Resources", link:"guide/topics/resources/animation-resource.html",
    tags:[], type:"guide" },
  { label:"String Resources", link:"guide/topics/resources/string-resource.html",
    tags:[], type:"guide" },
  { label:"Resource Types", link:"guide/topics/resources/available-resources.html",
    tags:[], type:"guide" },
  { label:"Providing Resources", link:"guide/topics/resources/providing-resources.html",
    tags:[], type:"guide" },
  { label:"Localizing with Resources", link:"guide/topics/resources/localization.html",
    tags:["localizing","localization","resources","formats","l10n"], type:"guide" },
  { label:"Menu Resource", link:"guide/topics/resources/menu-resource.html",
    tags:[], type:"guide" },
  { label:"Color State List Resource", link:"guide/topics/resources/color-list-resource.html",
    tags:[], type:"guide" },
  { label:"Application Resources", link:"guide/topics/resources/resources-i18n.html",
    tags:[], type:"guide" },
  { label:"Layout Resource", link:"guide/topics/resources/layout-resource.html",
    tags:[], type:"guide" },
  { label:"Handling Runtime Changes", link:"guide/topics/resources/runtime-changes.html",
    tags:["activity","lifecycle"], type:"guide" },
  { label:"Drawable Resources", link:"guide/topics/resources/drawable-resource.html",
    tags:[], type:"guide" },
  { label:"Android Interface Definition Language (AIDL)", link:"guide/components/aidl.html",
    tags:[], type:"guide" },
  { label:"App Components", link:"guide/components/index.html",
    tags:[], type:"guide" },
  { label:"Loaders", link:"guide/components/loaders.html",
    tags:[], type:"guide" },
  { label:"Services", link:"guide/components/services.html",
    tags:[], type:"guide" },
  { label:"Bound Services", link:"guide/components/bound-services.html",
    tags:[], type:"guide" },
  { label:"Application Fundamentals", link:"guide/components/fundamentals.html",
    tags:[], type:"guide" },
  { label:"Activities", link:"guide/components/activities.html",
    tags:["activity","intent"], type:"guide" },
  { label:"Fragments", link:"guide/components/fragments.html",
    tags:[], type:"guide" },
  { label:"Intents and Intent Filters", link:"guide/components/intents-filters.html",
    tags:[], type:"guide" },
  { label:"Processes and Threads", link:"guide/components/processes-and-threads.html",
    tags:["lifecycle","background"], type:"guide" },
  { label:"Tasks and Back Stack", link:"guide/components/tasks-and-back-stack.html",
    tags:[], type:"guide" },
  { label:"Application Design Goals", link:"guide/practices/app-design/index.html",
    tags:[], type:"guide" },
  { label:"Designing for Seamlessness", link:"guide/practices/app-design/seamlessness.html",
    tags:[], type:"guide" },
  { label:"Supporting Tablets and Handsets", link:"guide/practices/tablets-and-handsets.html",
    tags:[], type:"guide" },
  { label:"Supporting Multiple Screens", link:"guide/practices/screens_support.html",
    tags:[], type:"guide" },
  { label:"Web Apps", link:"guide/webapps/index.html",
    tags:[], type:"guide" },
  { label:"Targeting Screens from Web Apps", link:"guide/webapps/targeting.html",
    tags:[], type:"guide" },
  { label:"Best Practices for Web Apps", link:"guide/webapps/best-practices.html",
    tags:[], type:"guide" },
  { label:"Web Apps Overview", link:"guide/webapps/overview.html",
    tags:[], type:"guide" },
  { label:"Migrating to WebView in Android 4.4", link:"guide/webapps/migrating.html",
    tags:[], type:"guide" },
  { label:"Debugging Web Apps", link:"guide/webapps/debugging.html",
    tags:[], type:"guide" },
  { label:"Building Web Apps in WebView", link:"guide/webapps/webview.html",
    tags:[], type:"guide" },
  { label:"Design", link:"design/index.html",
    tags:[], type:"design" },
  { label:"Pure Android", link:"design/patterns/pure-android.html",
    tags:[], type:"design" },
  { label:"Multi-pane Layouts", link:"design/patterns/multi-pane-layouts.html",
    tags:["tablet","navigation","layout","fragment"], type:"design" },
  { label:"Patterns", link:"design/patterns/index.html",
    tags:[], type:"design" },
  { label:"Settings", link:"design/patterns/settings.html",
    tags:["preferences","sharedpreferences"], type:"design" },
  { label:"Backwards Compatibility", link:"design/patterns/compatibility.html",
    tags:["support"], type:"design" },
  { label:"App Structure", link:"design/patterns/app-structure.html",
    tags:["navigation","layout","tablet"], type:"design" },
  { label:"Full Screen", link:"design/patterns/fullscreen.html",
    tags:["full screen","immersive","leanback"], type:"design" },
  { label:"Help", link:"design/patterns/help.html",
    tags:["settings","preferences"], type:"design" },
  { label:"Confirming &amp; Acknowledging", link:"design/patterns/confirming-acknowledging.html",
    tags:["dialog","toast","notification"], type:"design" },
  { label:"Navigation Drawer", link:"design/patterns/navigation-drawer.html",
    tags:["DrawerLayout","SlidingPaneLayout"], type:"design" },
  { label:"Widgets", link:"design/patterns/widgets.html",
    tags:["appwidget","home"], type:"design" },
  { label:"Action Bar", link:"design/patterns/actionbar.html",
    tags:["actionbar","navigation"], type:"design" },
  { label:"New in Android", link:"design/patterns/new.html",
    tags:["KitKat","Android 4.4"], type:"design" },
  { label:"Selection", link:"design/patterns/selection.html",
    tags:["actionmode","navigation","contextual"], type:"design" },
  { label:"Swipe Views", link:"design/patterns/swipe-views.html",
    tags:["viewpager","navigation","tabs"], type:"design" },
  { label:"Navigation with Back and Up", link:"design/patterns/navigation.html",
    tags:["navigation","activity","task","up navigation","back navigation"], type:"design" },
  { label:"Accessibility", link:"design/patterns/accessibility.html",
    tags:["accessibility","navigation","input"], type:"design" },
  { label:"Gestures", link:"design/patterns/gestures.html",
    tags:["gesture","input","touch"], type:"design" },
  { label:"Notifications", link:"design/patterns/notifications.html",
    tags:[], type:"design" },
  { label:"Design Principles", link:"design/get-started/principles.html",
    tags:[], type:"design" },
  { label:"UI Overview", link:"design/get-started/ui-overview.html",
    tags:[], type:"design" },
  { label:"Creative Vision", link:"design/get-started/creative-vision.html",
    tags:[], type:"design" },
  { label:"Style", link:"design/style/index.html",
    tags:[], type:"design" },
  { label:"Devices and Displays", link:"design/style/devices-displays.html",
    tags:[], type:"design" },
  { label:"Writing Style", link:"design/style/writing.html",
    tags:["dialog","toast","notification"], type:"design" },
  { label:"Metrics and Grids", link:"design/style/metrics-grids.html",
    tags:["layout","screens"], type:"design" },
  { label:"Color", link:"design/style/color.html",
    tags:[], type:"design" },
  { label:"Themes", link:"design/style/themes.html",
    tags:[], type:"design" },
  { label:"Touch Feedback", link:"design/style/touch-feedback.html",
    tags:["input","button"], type:"design" },
  { label:"Iconography", link:"design/style/iconography.html",
    tags:["icons"], type:"design" },
  { label:"Your Branding", link:"design/style/branding.html",
    tags:["branding","logo"], type:"design" },
  { label:"Typography", link:"design/style/typography.html",
    tags:["textview","font"], type:"design" },
  { label:"Lists", link:"design/building-blocks/lists.html",
    tags:["listview","layout"], type:"design" },
  { label:"Building Blocks", link:"design/building-blocks/index.html",
    tags:[], type:"design" },
  { label:"Scrolling", link:"design/building-blocks/scrolling.html",
    tags:["scrollview","listview"], type:"design" },
  { label:"Pickers", link:"design/building-blocks/pickers.html",
    tags:["datepicker","timepicker"], type:"design" },
  { label:"Grid Lists", link:"design/building-blocks/grid-lists.html",
    tags:["gridview","layout","listview"], type:"design" },
  { label:"Seek Bars and Sliders", link:"design/building-blocks/seek-bars.html",
    tags:["seekbar","progressbar"], type:"design" },
  { label:"Spinners", link:"design/building-blocks/spinners.html",
    tags:["spinner","dropdown"], type:"design" },
  { label:"Switches", link:"design/building-blocks/switches.html",
    tags:["switch","checkbox","radiobutton","button"], type:"design" },
  { label:"Text Fields", link:"design/building-blocks/text-fields.html",
    tags:["text","edittext","input"], type:"design" },
  { label:"Buttons", link:"design/building-blocks/buttons.html",
    tags:["button","input"], type:"design" },
  { label:"Progress &amp; Activity", link:"design/building-blocks/progress.html",
    tags:["progressbar","download","network"], type:"design" },
  { label:"Dialogs", link:"design/building-blocks/dialogs.html",
    tags:["dialog","alert","popup","toast"], type:"design" },
  { label:"Tabs", link:"design/building-blocks/tabs.html",
    tags:["tabs","actionbar","navigation","viewpager"], type:"design" },
  { label:"Videos", link:"design/videos/index.html",
    tags:[], type:"design" },
  { label:"Downloads", link:"design/downloads/index.html",
    tags:[], type:"design" },
  { label:"Developer Tools", link:"tools/index.html",
    tags:[], type:"tools" },
  { label:"Managing Virtual Devices", link:"tools/devices/index.html",
    tags:[], type:"tools" },
  { label:"Using the Emulator", link:"tools/devices/emulator.html",
    tags:[], type:"tools" },
  { label:"Managing AVDs from the Command Line", link:"tools/devices/managing-avds-cmdline.html",
    tags:[], type:"tools" },
  { label:"Managing AVDs with AVD Manager", link:"tools/devices/managing-avds.html",
    tags:[], type:"tools" },
  { label:"Building and Running", link:"tools/building/index.html",
    tags:[], type:"tools" },
  { label:"Building and Running from Eclipse with ADT", link:"tools/building/building-eclipse.html",
    tags:[], type:"tools" },
  { label:"Building and Running from the Command Line", link:"tools/building/building-cmdline.html",
    tags:[], type:"tools" },
  { label:"Android NDK", link:"tools/sdk/ndk/index.html",
    tags:[], type:"tools" },
  { label:"ADT Plugin", link:"tools/sdk/eclipse-adt.html",
    tags:[], type:"tools" },
  { label:"Signing Your Applications", link:"tools/publishing/app-signing.html",
    tags:[], type:"tools" },
  { label:"Preparing for Release", link:"tools/publishing/preparing.html",
    tags:[], type:"tools" },
  { label:"Publishing Overview", link:"tools/publishing/publishing_overview.html",
    tags:[], type:"tools" },
  { label:"Versioning Your Applications", link:"tools/publishing/versioning.html",
    tags:[], type:"tools" },
  { label:"Testing", link:"tools/testing/index.html",
    tags:[], type:"tools" },
  { label:"Accessibility Testing Checklist", link:"tools/testing/testing_accessibility.html",
    tags:[], type:"tools" },
  { label:"Testing Fundamentals", link:"tools/testing/testing_android.html",
    tags:[], type:"tools" },
  { label:"Activity Testing", link:"tools/testing/activity_testing.html",
    tags:[], type:"tools" },
  { label:"Activity Testing Tutorial", link:"tools/testing/activity_test.html",
    tags:[], type:"tools" },
  { label:"Testing from Eclipse with ADT", link:"tools/testing/testing_eclipse.html",
    tags:[], type:"tools" },
  { label:"UI Testing", link:"tools/testing/testing_ui.html",
    tags:[], type:"tools" },
  { label:"Service Testing", link:"tools/testing/service_testing.html",
    tags:[], type:"tools" },
  { label:"Testing from Other IDEs", link:"tools/testing/testing_otheride.html",
    tags:[], type:"tools" },
  { label:"Content Provider Testing", link:"tools/testing/contentprovider_testing.html",
    tags:[], type:"tools" },
  { label:"What To Test", link:"tools/testing/what_to_test.html",
    tags:[], type:"tools" },
  { label:"Revisions", link:"tools/revisions/index.html",
    tags:[], type:"tools" },
  { label:"Platforms", link:"tools/revisions/platforms.html",
    tags:[], type:"tools" },
  { label:"Support Library", link:"tools/support-library/index.html",
    tags:[], type:"tools" },
  { label:"Support Library Setup", link:"tools/support-library/setup.html",
    tags:[], type:"tools" },
  { label:"Support Library Features", link:"tools/support-library/features.html",
    tags:[], type:"tools" },
  { label:"Samples", link:"tools/samples/index.html",
    tags:["example","code"], type:"tools" },
  { label:"Managing Projects from Eclipse with ADT", link:"tools/projects/projects-eclipse.html",
    tags:[], type:"tools" },
  { label:"Managing Projects", link:"tools/projects/index.html",
    tags:[], type:"tools" },
  { label:"Managing Projects from the Command Line", link:"tools/projects/projects-cmdline.html",
    tags:[], type:"tools" },
  { label:"Using Code Templates", link:"tools/projects/templates.html",
    tags:[], type:"tools" },
  { label:"Introduction", link:"tools/workflow/index.html",
    tags:[], type:"tools" },
  { label:"Extras", link:"tools/extras/index.html",
    tags:[], type:"tools" },
  { label:"OEM USB Drivers", link:"tools/extras/oem-usb.html",
    tags:[], type:"tools" },
  { label:"Debugging", link:"tools/debugging/index.html",
    tags:[], type:"tools" },
  { label:"Using DDMS", link:"tools/debugging/ddms.html",
    tags:[], type:"tools" },
  { label:"Reading and Writing Logs", link:"tools/debugging/debugging-log.html",
    tags:[], type:"tools" },
  { label:"Debugging from Other IDEs", link:"tools/debugging/debugging-projects-cmdline.html",
    tags:[], type:"tools" },
  { label:"Debugging from Eclipse with ADT", link:"tools/debugging/debugging-projects.html",
    tags:[], type:"tools" },
  { label:"Optimizing Your UI", link:"tools/debugging/debugging-ui.html",
    tags:[], type:"tools" },
  { label:"Profiling with Traceview and dmtracedump", link:"tools/debugging/debugging-tracing.html",
    tags:[], type:"tools" },
  { label:"Investigating Your RAM Usage", link:"tools/debugging/debugging-memory.html",
    tags:["memory","OutOfMemoryError"], type:"tools" },
  { label:"Improving Your Code with lint", link:"tools/debugging/improving-w-lint.html",
    tags:[], type:"tools" },
  { label:"Analyzing Display and Performance with Systrace", link:"tools/debugging/systrace.html",
    tags:[], type:"tools" },
  { label:"Using the Dev Tools App", link:"tools/debugging/debugging-devtools.html",
    tags:[], type:"tools" },
  { label:"Accessory Development Kit", link:"tools/adk/index.html",
    tags:["adk"], type:"tools" },
  { label:"Accessory Development Kit 2011 Guide", link:"tools/adk/adk.html",
    tags:["adk"], type:"tools" },
  { label:"Accessory Development Kit 2012 Guide", link:"tools/adk/adk2.html",
    tags:["adk"], type:"tools" },
  { label:"Using Hardware Devices", link:"tools/device.html",
    tags:[], type:"tools" },
  { label:"Introduction", link:"tools/workflow.html",
    tags:[], type:"tools" },
  { label:"Configurator", link:"tools/help/uiautomator/Configurator.html",
    tags:[], type:"tools" },
  { label:"uiautomator", link:"tools/help/uiautomator/index.html",
    tags:[], type:"tools" },
  { label:"UiCollection", link:"tools/help/uiautomator/UiCollection.html",
    tags:[], type:"tools" },
  { label:"UiWatcher", link:"tools/help/uiautomator/UiWatcher.html",
    tags:[], type:"tools" },
  { label:"UiScrollable", link:"tools/help/uiautomator/UiScrollable.html",
    tags:[], type:"tools" },
  { label:"UiAutomatorTestCase", link:"tools/help/uiautomator/UiAutomatorTestCase.html",
    tags:[], type:"tools" },
  { label:"UiSelector", link:"tools/help/uiautomator/UiSelector.html",
    tags:[], type:"tools" },
  { label:"IAutomationSupport", link:"tools/help/uiautomator/IAutomationSupport.html",
    tags:[], type:"tools" },
  { label:"UiObject", link:"tools/help/uiautomator/UiObject.html",
    tags:[], type:"tools" },
  { label:"UiObjectNotFoundException", link:"tools/help/uiautomator/UiObjectNotFoundException.html",
    tags:[], type:"tools" },
  { label:"UiDevice", link:"tools/help/uiautomator/UiDevice.html",
    tags:[], type:"tools" },
  { label:"MonkeyDevice", link:"tools/help/MonkeyDevice.html",
    tags:[], type:"tools" },
  { label:"Tools Help", link:"tools/help/index.html",
    tags:[], type:"tools" },
  { label:"monkeyrunner", link:"tools/help/monkeyrunner_concepts.html",
    tags:[], type:"tools" },
  { label:"Tracer for OpenGL ES", link:"tools/help/gltracer.html",
    tags:[], type:"tools" },
  { label:"MonkeyImage", link:"tools/help/MonkeyImage.html",
    tags:[], type:"tools" },
  { label:"Hierarchy Viewer", link:"tools/help/hierarchy-viewer.html",
    tags:[], type:"tools" },
  { label:"layoutopt", link:"tools/help/layoutopt.html",
    tags:[], type:"tools" },
  { label:"Device Monitor", link:"tools/help/monitor.html",
    tags:[], type:"tools" },
  { label:"etc1tool", link:"tools/help/etc1tool.html",
    tags:[], type:"tools" },
  { label:"Android Emulator", link:"tools/help/emulator.html",
    tags:[], type:"tools" },
  { label:"dmtracedump", link:"tools/help/dmtracedump.html",
    tags:[], type:"tools" },
  { label:"AVD Manager", link:"tools/help/avd-manager.html",
    tags:[], type:"tools" },
  { label:"HPROF Converter", link:"tools/help/hprof-conv.html",
    tags:[], type:"tools" },
  { label:"mksdcard", link:"tools/help/mksdcard.html",
    tags:[], type:"tools" },
  { label:"MonkeyRunner", link:"tools/help/MonkeyRunner.html",
    tags:[], type:"tools" },
  { label:"bmgr", link:"tools/help/bmgr.html",
    tags:[], type:"tools" },
  { label:"Traceview", link:"tools/help/traceview.html",
    tags:[], type:"tools" },
  { label:"Android Developer Tools", link:"tools/help/adt.html",
    tags:["adt"], type:"tools" },
  { label:"ProGuard", link:"tools/help/proguard.html",
    tags:[], type:"tools" },
  { label:"Systrace", link:"tools/help/systrace.html",
    tags:[], type:"tools" },
  { label:"lint", link:"tools/help/lint.html",
    tags:[], type:"tools" },
  { label:"zipalign", link:"tools/help/zipalign.html",
    tags:[], type:"tools" },
  { label:"Android Debug Bridge", link:"tools/help/adb.html",
    tags:["adb"], type:"tools" },
  { label:"Draw 9-patch", link:"tools/help/draw9patch.html",
    tags:["NinePatch"], type:"tools" },
  { label:"UI/Application Exerciser Monkey", link:"tools/help/monkey.html",
    tags:[], type:"tools" },
  { label:"android", link:"tools/help/android.html",
    tags:[], type:"tools" },
  { label:"SDK Manager", link:"tools/help/sdk-manager.html",
    tags:[], type:"tools" },
  { label:"logcat", link:"tools/help/logcat.html",
    tags:[], type:"tools" },
  { label:"JOBB", link:"tools/help/jobb.html",
    tags:[], type:"tools" },
  { label:"sqlite3", link:"tools/help/sqlite3.html",
    tags:[], type:"tools" }
];
